(() => {
'use strict';
const OPEN_METEO_URL='https://api.open-meteo.com/v1/forecast',STORAGE_KEY='bangs-survival-v1',SEOUL={latitude:37.5665,longitude:126.9780,label:'서울특별시 중구'},logic=window.BangsLogic,mapApi=window.BangsMap;
const state={lastPosition:null,selectedPosition:null,lastForecast:null,mapPicker:null,settings:loadSettings()};
const el={permissionCard:document.querySelector('#permissionCard'),loadingCard:document.querySelector('#loadingCard'),errorCard:document.querySelector('#errorCard'),forecastView:document.querySelector('#forecastView'),locationButton:document.querySelector('#locationButton'),demoButton:document.querySelector('#demoButton'),retryButton:document.querySelector('#retryButton'),errorMessage:document.querySelector('#errorMessage'),locationLabel:document.querySelector('#locationLabel'),updatedLabel:document.querySelector('#updatedLabel'),gridLabel:document.querySelector('#gridLabel'),sourceBadge:document.querySelector('#sourceBadge'),editLocationButton:document.querySelector('#editLocationButton'),mapPanel:document.querySelector('#mapPanel'),mapContainer:document.querySelector('#map'),mapStatus:document.querySelector('#mapStatus'),applyMapPositionButton:document.querySelector('#applyMapPositionButton'),scoreRing:document.querySelector('#scoreRing'),scoreValue:document.querySelector('#scoreValue'),verdictBadge:document.querySelector('#verdictBadge'),verdictTitle:document.querySelector('#verdictTitle'),verdictDescription:document.querySelector('#verdictDescription'),reasonChips:document.querySelector('#reasonChips'),mascot:document.querySelector('#mascot'),mascotStatus:document.querySelector('#mascotStatus'),adviceList:document.querySelector('#adviceList'),bestWindowTitle:document.querySelector('#bestWindowTitle'),bestWindowDescription:document.querySelector('#bestWindowDescription'),timeline:document.querySelector('#timeline'),feedbackStatus:document.querySelector('#feedbackStatus'),dataSourceLabel:document.querySelector('#dataSourceLabel'),settingsButton:document.querySelector('#settingsButton'),settingsDialog:document.querySelector('#settingsDialog'),saveSettingsButton:document.querySelector('#saveSettingsButton')};
init();
function init(){if(!logic){showError('앱 로직을 불러오지 못했습니다. 새로고침해 주세요.');return;}el.locationButton.addEventListener('click',requestCurrentLocation);el.demoButton.addEventListener('click',()=>usePosition(SEOUL));el.retryButton.addEventListener('click',()=>state.lastPosition?usePosition(state.lastPosition):requestCurrentLocation());el.editLocationButton.addEventListener('click',openLocationPicker);el.applyMapPositionButton.addEventListener('click',applySelectedMapPosition);el.settingsButton.addEventListener('click',openSettings);el.saveSettingsButton.addEventListener('click',saveSettingsFromDialog);document.querySelectorAll('[data-feedback]').forEach((button)=>button.addEventListener('click',()=>saveFeedback(button.dataset.feedback)));if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));}
function requestCurrentLocation(){if(!navigator.geolocation){showError('이 브라우저에서는 위치 기능을 사용할 수 없습니다. 서울 예시를 이용해 주세요.');return;}showLoading();navigator.geolocation.getCurrentPosition((position)=>usePosition({latitude:position.coords.latitude,longitude:position.coords.longitude,label:'현재 위치'}),(error)=>showError(error.code===error.PERMISSION_DENIED?'위치 권한이 꺼져 있습니다. 권한을 허용하거나 서울 예시를 이용해 주세요.':'현재 위치를 확인하지 못했습니다. 네트워크와 위치 설정을 확인해 주세요.'),{enableHighAccuracy:true,timeout:10000,maximumAge:300000});}
async function usePosition(position){const resolved=await resolvePositionLabel(position);state.lastPosition=resolved;state.selectedPosition=resolved;await fetchForecast(resolved);}
async function resolvePositionLabel(position){if(!mapApi)return position;const region=await mapApi.resolveRegion(position);return region?{...position,label:region.label,region}:position;}
async function fetchForecast(position){state.lastPosition=position;showLoading();try{const kma=await fetchKmaForecast(position);if(kma){const forecast=buildForecastFromHours(kma.hours,position.label,'KMA',kma.grid);state.lastForecast=forecast;renderForecast(forecast);return;}const fallback=await fetchOpenMeteoForecast(position);const forecast=buildForecastFromOpenMeteo(fallback,position.label);state.lastForecast=forecast;renderForecast(forecast);}catch(error){console.error(error);showError('날씨 데이터를 불러오지 못했습니다. 잠시 뒤 다시 시도해 주세요.');}}
async function fetchKmaForecast(position){try{const params=new URLSearchParams({lat:String(position.latitude),lon:String(position.longitude)});const response=await fetch(`/api/weather?${params}`);if(!response.ok)return null;const payload=await response.json();return payload.source==='KMA'&&Array.isArray(payload.hours)?payload:null;}catch{return null;}}
async function fetchOpenMeteoForecast(position){const params=new URLSearchParams({latitude:String(position.latitude),longitude:String(position.longitude),hourly:'temperature_2m,relative_humidity_2m,dew_point_2m,precipitation_probability,wind_speed_10m',forecast_days:'2',timezone:'auto'});const response=await fetch(`${OPEN_METEO_URL}?${params}`);if(!response.ok)throw new Error(`weather_http_${response.status}`);return response.json();}
function buildForecastFromHours(rawHours,label,source,grid){const calibration=logic.getCalibrationOffset(state.settings.feedback),sensitivity=logic.getSensitivityOffset(state.settings.sensitivity);const hours=rawHours.slice(0,12).map((hour)=>{const metrics={temperature:safeNumber(hour.metrics.temperature),humidity:safeNumber(hour.metrics.humidity),dewPoint:safeNumber(hour.metrics.dewPoint),precipitation:safeNumber(hour.metrics.precipitation),wind:safeNumber(hour.metrics.wind)};const baseRisk=logic.calculateBaseRisk(metrics),risk=logic.clamp(baseRisk+sensitivity+calibration,0,1);return{time:hour.time,metrics,baseRisk,risk,score:Math.round((1-risk)*100)};});if(!hours.length)throw new Error('weather_hours_missing');return{label,source,grid,generatedAt:new Date(),current:hours[0],hours,best:hours.reduce((best,hour)=>hour.score>best.score?hour:best,hours[0]),calibration};}
function buildForecastFromOpenMeteo(data,label){const hourly=data.hourly;if(!hourly?.time?.length)throw new Error('weather_payload_invalid');const now=Date.now();let startIndex=hourly.time.findIndex((time)=>new Date(time).getTime()>=now-1800000);if(startIndex<0)startIndex=0;const rawHours=[];for(let i=startIndex;i<Math.min(startIndex+12,hourly.time.length);i+=1){rawHours.push({time:hourly.time[i],metrics:{temperature:safeNumber(hourly.temperature_2m[i]),humidity:safeNumber(hourly.relative_humidity_2m[i]),dewPoint:safeNumber(hourly.dew_point_2m[i]),precipitation:safeNumber(hourly.precipitation_probability[i]),wind:safeNumber(hourly.wind_speed_10m[i])}});}return buildForecastFromHours(rawHours,label,'Open-Meteo fallback',logic.toKmaGrid(state.lastPosition.latitude,state.lastPosition.longitude));}
function renderForecast(forecast){state.lastForecast=forecast;showOnly('forecast');const current=forecast.current,verdict=logic.getVerdict(current.score),advice=logic.getBangsAdvice(current.score,current.metrics);el.locationLabel.textContent=forecast.label||'선택한 위치';el.updatedLabel.textContent=`${formatTime(forecast.generatedAt)} 기준`;el.gridLabel.textContent=forecast.grid?`기상청 격자 ${forecast.grid.nx}, ${forecast.grid.ny}`:'';el.sourceBadge.textContent=forecast.source==='KMA'?'기상청 동네예보':'대체 예보';el.dataSourceLabel.textContent=forecast.source==='KMA'?'기상청 동네예보':'Open-Meteo fallback';el.scoreValue.textContent=String(current.score);el.scoreRing.style.setProperty('--score-angle',`${current.score*3.6}deg`);el.verdictBadge.textContent=verdict.badge;el.verdictTitle.textContent=verdict.title;el.verdictDescription.textContent=verdict.description;el.mascot.dataset.mood=verdict.key;el.mascotStatus.textContent=({great:'오늘 나 꽤 멀쩡해!',okay:'고정력만 조금 빌려줘.',worried:'습기가 수상한데…',doomed:'오늘은 나를 놓아줘…'})[verdict.key];el.reasonChips.replaceChildren(...getReasons(current.metrics).map((reason)=>{const chip=document.createElement('span');chip.className='reason-chip';chip.textContent=reason;return chip;}));el.adviceList.replaceChildren(...advice.map((entry)=>{const item=document.createElement('article');item.className='advice-item';const title=document.createElement('strong');title.textContent=entry.title;const description=document.createElement('p');description.textContent=entry.description;item.append(title,description);return item;}));const bestDate=new Date(forecast.best.time);el.bestWindowTitle.textContent=`${formatHour(bestDate)} 전후가 가장 안전해요`;el.bestWindowDescription.textContent=`예상 생존점수 ${forecast.best.score}점입니다. 외출 시간을 조절할 수 있다면 이 시간대가 앞으로 12시간 중 가장 유리합니다.`;el.timeline.replaceChildren(...forecast.hours.map((hour)=>createTimelineItem(hour,hour===forecast.best)));renderFeedbackState(forecast);}
async function openLocationPicker(){el.mapPanel.classList.remove('hidden');el.mapStatus.textContent='지도를 준비하는 중입니다.';if(!mapApi){el.mapStatus.textContent='지도 모듈을 불러오지 못했습니다.';return;}if(!state.mapPicker){state.mapPicker=await mapApi.createPicker(el.mapContainer,state.lastPosition,({latitude,longitude,region})=>{state.selectedPosition={latitude,longitude,label:region?.label||'지도에서 선택한 위치',region};const grid=logic.toKmaGrid(latitude,longitude);el.mapStatus.textContent=`${state.selectedPosition.label} · 기상청 격자 ${grid.nx}, ${grid.ny}`;});}else{state.mapPicker.setPosition(state.lastPosition);state.mapPicker.relayout();}if(!state.mapPicker){el.mapStatus.textContent='카카오맵 JavaScript 키가 아직 설정되지 않았습니다. Vercel 환경변수를 확인해 주세요.';return;}const region=await mapApi.resolveRegion(state.lastPosition),grid=logic.toKmaGrid(state.lastPosition.latitude,state.lastPosition.longitude);el.mapStatus.textContent=`${region?.label||state.lastPosition.label} · 기상청 격자 ${grid.nx}, ${grid.ny}`;}
async function applySelectedMapPosition(){if(!state.selectedPosition)return;el.mapPanel.classList.add('hidden');await usePosition(state.selectedPosition);}
function renderFeedbackState(forecast){const day=logic.feedbackDayKey(forecast.current.time),today=logic.getDailyFeedback(state.settings.feedback,day);document.querySelectorAll('[data-feedback]').forEach((button)=>{const selected=button.dataset.feedback===today?.type;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));});const count=state.settings.feedback.length;if(today){el.feedbackStatus.textContent=`오늘 결과는 '${logic.getFeedbackLabel(today.type)}'으로 기록되어 있습니다. 다른 버튼을 누르면 수정됩니다. 총 ${count}일 기록.`;return;}el.feedbackStatus.textContent=count>=3?`총 ${count}일 결과를 반영해 약 ${Math.round(Math.abs(forecast.calibration)*100)}점 범위에서 개인 보정 중입니다.`:`${count}/3일 기록됨. 3일부터 개인 보정을 시작합니다.`;}
function createTimelineItem(hour,isBest){const item=document.createElement('div');item.className=`timeline-item${isBest?' best':''}`;item.setAttribute('role','listitem');const riskLabel=hour.score>=70?'안전':hour.score>=45?'주의':'위험';item.innerHTML=`<span class="timeline-time">${escapeHtml(formatHour(new Date(hour.time)))}</span><strong class="timeline-score">${hour.score}</strong><span class="timeline-risk">${riskLabel}</span>`;return item;}
function getReasons(metrics){return[{severity:logic.smoothstep(50,88,metrics.humidity),text:`습도 ${Math.round(metrics.humidity)}%`},{severity:logic.smoothstep(8,24,metrics.dewPoint),text:`이슬점 ${Math.round(metrics.dewPoint)}℃`},{severity:logic.clamp(metrics.precipitation/100,0,1),text:`비 ${Math.round(metrics.precipitation)}%`},{severity:logic.smoothstep(6,28,metrics.wind),text:`바람 ${Math.round(metrics.wind)}km/h`}].sort((a,b)=>b.severity-a.severity).map((entry)=>entry.text);}
function saveFeedback(type){if(!state.lastForecast)return;const actualRisk={survived:.18,shaky:.55,failed:.9}[type];if(actualRisk===undefined)return;const day=logic.feedbackDayKey(state.lastForecast.current.time);state.settings.feedback=logic.upsertDailyFeedback(state.settings.feedback,{at:new Date().toISOString(),day,type,predictedRisk:state.lastForecast.current.baseRisk,actualRisk});persistSettings();renderForecast(recalibrate(state.lastForecast));}
function recalibrate(forecast){const calibration=logic.getCalibrationOffset(state.settings.feedback),sensitivity=logic.getSensitivityOffset(state.settings.sensitivity);const hours=forecast.hours.map((hour)=>{const risk=logic.clamp(hour.baseRisk+sensitivity+calibration,0,1);return{...hour,risk,score:Math.round((1-risk)*100)};});return{...forecast,generatedAt:new Date(),current:hours[0],hours,best:hours.reduce((best,hour)=>hour.score>best.score?hour:best,hours[0]),calibration};}
function openSettings(){const selected=el.settingsDialog.querySelector(`input[name="sensitivity"][value="${state.settings.sensitivity}"]`);if(selected)selected.checked=true;el.settingsDialog.showModal();}
function saveSettingsFromDialog(event){event.preventDefault();const selected=el.settingsDialog.querySelector('input[name="sensitivity"]:checked');state.settings.sensitivity=selected?.value||'normal';persistSettings();el.settingsDialog.close();if(state.lastForecast)renderForecast(recalibrate(state.lastForecast));}
function loadSettings(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');const feedback=Array.isArray(parsed.feedback)?parsed.feedback.map(logic?.normalizeFeedbackSample||((sample)=>sample)).filter(Boolean).slice(-30):[];return{sensitivity:['low','normal','high'].includes(parsed.sensitivity)?parsed.sensitivity:'normal',feedback};}catch{return{sensitivity:'normal',feedback:[]};}}
function persistSettings(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.settings));}function showLoading(){showOnly('loading');}function showError(message){if(el.errorMessage)el.errorMessage.textContent=message;showOnly('error');}function showOnly(target){el.permissionCard?.classList.toggle('hidden',target!=='permission');el.loadingCard?.classList.toggle('hidden',target!=='loading');el.errorCard?.classList.toggle('hidden',target!=='error');el.forecastView?.classList.toggle('hidden',target!=='forecast');}function safeNumber(value){const number=Number(value);return Number.isFinite(number)?number:0;}function formatTime(date){return new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit'}).format(date);}function formatHour(date){return new Intl.DateTimeFormat('ko-KR',{hour:'numeric',timeZone:'Asia/Seoul'}).format(date);}function escapeHtml(value){return String(value).replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
})();
