(() => {
  'use strict';
  const OPEN_METEO_URL = 'https://api.open-meteo.com/v1/forecast';
  const STORAGE_KEY = 'bangs-survival-v1';
  const SEOUL = { latitude: 37.5665, longitude: 126.9780, label: '서울 예시' };
  const logic = window.BangsLogic;
  const state = { lastPosition: null, lastForecast: null, settings: loadSettings() };
  const el = { permissionCard:document.querySelector('#permissionCard'),loadingCard:document.querySelector('#loadingCard'),errorCard:document.querySelector('#errorCard'),forecastView:document.querySelector('#forecastView'),locationButton:document.querySelector('#locationButton'),demoButton:document.querySelector('#demoButton'),retryButton:document.querySelector('#retryButton'),errorMessage:document.querySelector('#errorMessage'),locationLabel:document.querySelector('#locationLabel'),updatedLabel:document.querySelector('#updatedLabel'),scoreRing:document.querySelector('#scoreRing'),scoreValue:document.querySelector('#scoreValue'),verdictBadge:document.querySelector('#verdictBadge'),verdictTitle:document.querySelector('#verdictTitle'),verdictDescription:document.querySelector('#verdictDescription'),reasonChips:document.querySelector('#reasonChips'),bestWindowTitle:document.querySelector('#bestWindowTitle'),bestWindowDescription:document.querySelector('#bestWindowDescription'),timeline:document.querySelector('#timeline'),feedbackStatus:document.querySelector('#feedbackStatus'),mascot:document.querySelector('#mascot'),mascotStatus:document.querySelector('#mascotStatus'),settingsButton:document.querySelector('#settingsButton'),settingsDialog:document.querySelector('#settingsDialog'),saveSettingsButton:document.querySelector('#saveSettingsButton') };
  init();
  function init(){ if(!logic){showError('앱 로직을 불러오지 못했습니다. 새로고침해 주세요.');return;} el.locationButton.addEventListener('click',requestCurrentLocation);el.demoButton.addEventListener('click',()=>fetchForecast(SEOUL));el.retryButton.addEventListener('click',()=>state.lastPosition?fetchForecast(state.lastPosition):requestCurrentLocation());el.settingsButton.addEventListener('click',openSettings);el.saveSettingsButton.addEventListener('click',saveSettingsFromDialog);document.querySelectorAll('[data-feedback]').forEach((b)=>b.addEventListener('click',()=>saveFeedback(b.dataset.feedback)));if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{})); }
  function requestCurrentLocation(){if(!navigator.geolocation)return showError('이 브라우저에서는 위치 기능을 사용할 수 없습니다. 서울 예시를 이용해 주세요.');showLoading();navigator.geolocation.getCurrentPosition((p)=>fetchForecast({latitude:p.coords.latitude,longitude:p.coords.longitude,label:'현재 위치'}),(e)=>showError(e.code===e.PERMISSION_DENIED?'위치 권한이 꺼져 있습니다. 권한을 허용하거나 서울 예시를 이용해 주세요.':'현재 위치를 확인하지 못했습니다. 네트워크와 위치 설정을 확인해 주세요.'),{enableHighAccuracy:false,timeout:10000,maximumAge:600000});}
  async function fetchForecast(position){state.lastPosition=position;showLoading();const params=new URLSearchParams({latitude:String(position.latitude),longitude:String(position.longitude),hourly:'temperature_2m,relative_humidity_2m,dew_point_2m,precipitation_probability,wind_speed_10m',forecast_days:'2',timezone:'auto'});try{const response=await fetch(`${OPEN_METEO_URL}?${params}`);if(!response.ok)throw new Error(`weather_http_${response.status}`);const forecast=buildForecast(await response.json(),position.label);state.lastForecast=forecast;renderForecast(forecast);}catch(error){console.error(error);showError('날씨 제공자와 통신하지 못했습니다. 잠시 뒤 다시 시도해 주세요.');}}
  function buildForecast(data,label){const hourly=data.hourly;if(!hourly?.time?.length)throw new Error('weather_payload_invalid');const now=Date.now();let startIndex=hourly.time.findIndex((time)=>new Date(time).getTime()>=now-1800000);if(startIndex<0)startIndex=0;const calibration=logic.getCalibrationOffset(state.settings.feedback);const sensitivity=logic.getSensitivityOffset(state.settings.sensitivity);const hours=[];for(let i=startIndex;i<Math.min(startIndex+12,hourly.time.length);i+=1){const metrics={temperature:safeNumber(hourly.temperature_2m[i]),humidity:safeNumber(hourly.relative_humidity_2m[i]),dewPoint:safeNumber(hourly.dew_point_2m[i]),precipitation:safeNumber(hourly.precipitation_probability[i]),wind:safeNumber(hourly.wind_speed_10m[i])};const baseRisk=logic.calculateBaseRisk(metrics);const risk=logic.clamp(baseRisk+sensitivity+calibration,0,1);hours.push({time:hourly.time[i],metrics,baseRisk,risk,score:Math.round((1-risk)*100)});}if(!hours.length)throw new Error('weather_hours_missing');return{label,generatedAt:new Date(),current:hours[0],hours,best:hours.reduce((a,b)=>b.score>a.score?b:a,hours[0]),calibration};}
  function renderForecast(f){state.lastForecast=f;showOnly('forecast');const c=f.current,v=logic.getVerdict(c.score);el.locationLabel.textContent=f.label;el.updatedLabel.textContent=`${formatTime(f.generatedAt)} 기준`;el.scoreValue.textContent=String(c.score);el.scoreRing.style.setProperty('--score-angle',`${c.score*3.6}deg`);el.verdictBadge.textContent=v.badge;el.verdictTitle.textContent=v.title;el.verdictDescription.textContent=v.description;el.mascot.dataset.mood=v.key;el.mascotStatus.textContent=({great:'오늘 나 꽤 멀쩡해!',okay:'고정력만 조금 빌려줘.',worried:'습기가 수상한데…',doomed:'오늘은 나를 놓아줘…'})[v.key];el.reasonChips.replaceChildren(...getReasons(c.metrics).map((r)=>{const chip=document.createElement('span');chip.className='reason-chip';chip.textContent=r;return chip;}));const bestDate=new Date(f.best.time);el.bestWindowTitle.textContent=`${formatHour(bestDate)} 전후가 가장 안전해요`;el.bestWindowDescription.textContent=`예상 생존점수 ${f.best.score}점입니다. 외출 시간을 조절할 수 있다면 이 시간대가 오늘 12시간 중 가장 유리합니다.`;el.timeline.replaceChildren(...f.hours.map((h)=>createTimelineItem(h,h===f.best)));renderFeedbackState(f);}
  function renderFeedbackState(f){const day=logic.feedbackDayKey(f.current.time),today=logic.getDailyFeedback(state.settings.feedback,day);document.querySelectorAll('[data-feedback]').forEach((b)=>{const s=b.dataset.feedback===today?.type;b.classList.toggle('selected',s);b.setAttribute('aria-pressed',String(s));});const count=state.settings.feedback.length;if(today){el.feedbackStatus.textContent=`오늘 결과는 '${logic.getFeedbackLabel(today.type)}'으로 기록되어 있습니다. 다른 버튼을 누르면 수정됩니다. 총 ${count}일 기록.`;return;}el.feedbackStatus.textContent=count>=3?`총 ${count}일 결과를 반영해 약 ${Math.round(Math.abs(f.calibration)*100)}점 범위에서 개인 보정 중입니다.`:`${count}/3일 기록됨. 3일부터 개인 보정을 시작합니다.`;}
  function createTimelineItem(h,best){const item=document.createElement('div');item.className=`timeline-item${best?' best':''}`;item.setAttribute('role','listitem');const label=h.score>=70?'안전':h.score>=45?'주의':'위험';item.innerHTML=`<span class="timeline-time">${escapeHtml(formatHour(new Date(h.time)))}</span><strong class="timeline-score">${h.score}</strong><span class="timeline-risk">${label}</span>`;return item;}
  function getReasons(m){return[{severity:logic.smoothstep(50,88,m.humidity),text:`습도 ${Math.round(m.humidity)}%`},{severity:logic.smoothstep(8,24,m.dewPoint),text:`이슬점 ${Math.round(m.dewPoint)}℃`},{severity:logic.clamp(m.precipitation/100,0,1),text:`비 ${Math.round(m.precipitation)}%`},{severity:logic.smoothstep(6,28,m.wind),text:`바람 ${Math.round(m.wind)}km/h`}].sort((a,b)=>b.severity-a.severity).map((e)=>e.text);}
  function saveFeedback(type){if(!state.lastForecast)return;const actualRisk={survived:.18,shaky:.55,failed:.9}[type];if(actualRisk===undefined)return;const day=logic.feedbackDayKey(state.lastForecast.current.time);state.settings.feedback=logic.upsertDailyFeedback(state.settings.feedback,{at:new Date().toISOString(),day,type,predictedRisk:state.lastForecast.current.baseRisk,actualRisk});persistSettings();renderForecast(recalibrate(state.lastForecast));}
  function recalibrate(f){const calibration=logic.getCalibrationOffset(state.settings.feedback),sensitivity=logic.getSensitivityOffset(state.settings.sensitivity);const hours=f.hours.map((h)=>{const risk=logic.clamp(h.baseRisk+sensitivity+calibration,0,1);return{...h,risk,score:Math.round((1-risk)*100)};});return{...f,generatedAt:new Date(),current:hours[0],hours,best:hours.reduce((a,b)=>b.score>a.score?b:a,hours[0]),calibration};}
  function openSettings(){const s=el.settingsDialog.querySelector(`input[name="sensitivity"][value="${state.settings.sensitivity}"]`);if(s)s.checked=true;el.settingsDialog.showModal();}
  function saveSettingsFromDialog(e){e.preventDefault();const s=el.settingsDialog.querySelector('input[name="sensitivity"]:checked');state.settings.sensitivity=s?.value||'normal';persistSettings();el.settingsDialog.close();if(state.lastForecast)renderForecast(recalibrate(state.lastForecast));}
  function loadSettings(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');const feedback=Array.isArray(parsed.feedback)?parsed.feedback.map(logic?.normalizeFeedbackSample||((x)=>x)).filter(Boolean).slice(-30):[];return{sensitivity:['low','normal','high'].includes(parsed.sensitivity)?parsed.sensitivity:'normal',feedback};}catch{return{sensitivity:'normal',feedback:[]};}}
  function persistSettings(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.settings));}function showLoading(){showOnly('loading');}function showError(message){if(el.errorMessage)el.errorMessage.textContent=message;showOnly('error');}function showOnly(target){el.permissionCard?.classList.toggle('hidden',target!=='permission');el.loadingCard?.classList.toggle('hidden',target!=='loading');el.errorCard?.classList.toggle('hidden',target!=='error');el.forecastView?.classList.toggle('hidden',target!=='forecast');}function safeNumber(v){const n=Number(v);return Number.isFinite(n)?n:0;}function formatTime(d){return new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit'}).format(d);}function formatHour(d){return new Intl.DateTimeFormat('ko-KR',{hour:'numeric'}).format(d);}function escapeHtml(v){return String(v).replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
})();
