(function initBangsLogic(root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.BangsLogic = api;
}(typeof globalThis !== 'undefined' ? globalThis : this, () => {
  'use strict';
  const KMA_GRID = { RE:6371.00877, GRID:5.0, SLAT1:30.0, SLAT2:60.0, OLON:126.0, OLAT:38.0, XO:43, YO:136 };
  function clamp(value,min,max){return Math.min(max,Math.max(min,value));}
  function smoothstep(edge0,edge1,value){const t=clamp((value-edge0)/(edge1-edge0),0,1);return t*t*(3-(2*t));}
  function calculateBaseRisk({humidity,dewPoint,precipitation,wind}){const humidityRisk=smoothstep(50,88,humidity);const dewPointRisk=smoothstep(8,24,dewPoint);const rainRisk=clamp(precipitation/100,0,1);const windRisk=smoothstep(6,28,wind);let risk=(humidityRisk*.42)+(dewPointRisk*.25)+(rainRisk*.20)+(windRisk*.13);if(humidity>=82&&precipitation>=45)risk+=.08;if(humidity>=90)risk+=.05;return clamp(risk,0,1);}
  function calculateDewPoint(temperatureC,relativeHumidity){const humidity=clamp(Number(relativeHumidity),1,100);const temperature=Number(temperatureC);if(!Number.isFinite(temperature))return 0;const a=17.62,b=243.12;const gamma=Math.log(humidity/100)+((a*temperature)/(b+temperature));return (b*gamma)/(a-gamma);}
  function toKmaGrid(latitude,longitude){const lat=Number(latitude),lon=Number(longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))throw new TypeError('invalid_lat_lon');const DEGRAD=Math.PI/180;const re=KMA_GRID.RE/KMA_GRID.GRID;const slat1=KMA_GRID.SLAT1*DEGRAD,slat2=KMA_GRID.SLAT2*DEGRAD,olon=KMA_GRID.OLON*DEGRAD,olat=KMA_GRID.OLAT*DEGRAD;let sn=Math.tan((Math.PI*.25)+(slat2*.5))/Math.tan((Math.PI*.25)+(slat1*.5));sn=Math.log(Math.cos(slat1)/Math.cos(slat2))/Math.log(sn);let sf=Math.tan((Math.PI*.25)+(slat1*.5));sf=(Math.pow(sf,sn)*Math.cos(slat1))/sn;let ro=Math.tan((Math.PI*.25)+(olat*.5));ro=(re*sf)/Math.pow(ro,sn);let ra=Math.tan((Math.PI*.25)+(lat*DEGRAD*.5));ra=(re*sf)/Math.pow(ra,sn);let theta=(lon*DEGRAD)-olon;if(theta>Math.PI)theta-=2*Math.PI;if(theta<-Math.PI)theta+=2*Math.PI;theta*=sn;return{nx:Math.floor((ra*Math.sin(theta))+KMA_GRID.XO+.5),ny:Math.floor((ro-(ra*Math.cos(theta)))+KMA_GRID.YO+.5)};}
  function chooseKmaBaseDateTime(now=new Date()){const shifted=new Date(now.getTime()+(9*60*60*1000)-(10*60*1000));const year=shifted.getUTCFullYear(),month=shifted.getUTCMonth(),day=shifted.getUTCDate(),hour=shifted.getUTCHours();const candidates=[2,5,8,11,14,17,20,23];const selected=candidates.filter((candidate)=>candidate<=hour).at(-1);let base=new Date(Date.UTC(year,month,day,selected??23,0,0));if(selected===undefined)base=new Date(base.getTime()-(24*60*60*1000));const yyyy=String(base.getUTCFullYear()),mm=String(base.getUTCMonth()+1).padStart(2,'0'),dd=String(base.getUTCDate()).padStart(2,'0'),hh=String(base.getUTCHours()).padStart(2,'0');return{baseDate:`${yyyy}${mm}${dd}`,baseTime:`${hh}00`};}
  function parseKmaForecastItems(items,now=new Date()){if(!Array.isArray(items))return[];const groups=new Map();items.forEach((item)=>{const date=String(item.fcstDate||''),time=String(item.fcstTime||'').padStart(4,'0');if(!/^\d{8}$/.test(date)||!/^\d{4}$/.test(time))return;const key=`${date}${time}`;const group=groups.get(key)||{date,time,categories:{}};group.categories[item.category]=Number(item.fcstValue);groups.set(key,group);});const nowMs=now.getTime()-(30*60*1000);return[...groups.values()].map((group)=>{const{date,time,categories}=group;if(!Number.isFinite(categories.TMP)||!Number.isFinite(categories.REH))return null;const iso=`${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}T${time.slice(0,2)}:${time.slice(2,4)}:00+09:00`;const when=new Date(iso);const humidity=categories.REH,temperature=categories.TMP;return{time:iso,metrics:{temperature,humidity,dewPoint:calculateDewPoint(temperature,humidity),precipitation:Number.isFinite(categories.POP)?categories.POP:0,wind:Number.isFinite(categories.WSD)?categories.WSD*3.6:0}};}).filter((entry)=>entry&&new Date(entry.time).getTime()>=nowMs).sort((a,b)=>new Date(a.time)-new Date(b.time)).slice(0,12);}
  function distanceKm(a,b){const lat1=Number(a?.latitude),lon1=Number(a?.longitude),lat2=Number(b?.latitude),lon2=Number(b?.longitude);if(![lat1,lon1,lat2,lon2].every(Number.isFinite))return Infinity;const toRad=(value)=>value*Math.PI/180;const dLat=toRad(lat2-lat1),dLon=toRad(lon2-lon1);const p1=toRad(lat1),p2=toRad(lat2);const h=Math.sin(dLat/2)**2+(Math.cos(p1)*Math.cos(p2)*(Math.sin(dLon/2)**2));return 6371.0088*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
  function isSuspiciousLocationJump(current,saved,thresholdKm=10){const threshold=Number(thresholdKm);if(!Number.isFinite(threshold)||threshold<=0)return false;const distance=distanceKm(current,saved);return Number.isFinite(distance)&&distance>=threshold;}
  function normalizeSavedLocation(value){if(!value||typeof value!=='object')return null;const latitude=Number(value.latitude),longitude=Number(value.longitude);if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||latitude<-90||latitude>90||longitude<-180||longitude>180)return null;const label=typeof value.label==='string'&&value.label.trim()?value.label.trim().slice(0,120):'저장한 위치';const region=value.region&&typeof value.region==='object'?{label:typeof value.region.label==='string'?value.region.label.slice(0,120):label,district:typeof value.region.district==='string'?value.region.district.slice(0,80):'',neighborhood:typeof value.region.neighborhood==='string'?value.region.neighborhood.slice(0,80):'',code:typeof value.region.code==='string'?value.region.code.slice(0,32):''}:null;const savedAt=typeof value.savedAt==='string'&&!Number.isNaN(Date.parse(value.savedAt))?value.savedAt:new Date().toISOString();return{latitude,longitude,label,region,source:'saved',accuracy:null,savedAt};}
  function getSensitivityOffset(value){if(value==='low')return-.08;if(value==='high')return.10;return 0;}
  function getVerdict(score){if(score>=78)return{key:'great',badge:'오늘은 가능',title:'앞머리 해도 되겠어요',description:'현재 날씨 기준으로는 유지에 비교적 유리합니다. 그래도 장시간 야외 활동은 시간대별 점수를 확인해 주세요.'};if(score>=58)return{key:'okay',badge:'조금 애매함',title:'고정력 챙기면 도전 가능',description:'습기나 바람 중 하나가 방해할 수 있습니다. 오래 밖에 있다면 완벽하게 세팅할 날은 아닙니다.'};if(score>=38)return{key:'worried',badge:'주의',title:'오늘은 앞머리가 고생해요',description:'세팅해도 흐트러질 가능성이 높습니다. 고정 제품을 쓰거나 다른 스타일을 고려하는 편이 안전합니다.'};return{key:'doomed',badge:'비추천',title:'오늘은 하지 마세요',description:'습기·비·바람 조건이 앞머리 유지에 불리합니다. 공들인 시간이 아까울 가능성이 큽니다.'};}
  function getBangsAdvice(score,metrics){const advice=[];if(score>=78)advice.push({key:'base-good',title:'가볍게 세팅해도 괜찮아요',description:'오늘은 기본적인 고정만 하고 과하게 손대지 않아도 됩니다.'});else if(score>=58)advice.push({key:'base-mid',title:'고정 제품을 챙겨두세요',description:'외출 시간이 길다면 작은 빗이나 고정 제품을 챙기는 편이 낫습니다.'});else advice.push({key:'base-bad',title:'대체 스타일도 생각해두세요',description:'앞머리에 오래 공들이기보다 넘기거나 고정하는 스타일이 시간을 아낄 수 있습니다.'});if(metrics.precipitation>=40)advice.push({key:'rain',title:'비 노출을 최대한 줄이세요',description:'우산이나 후드로 앞머리에 직접 비가 닿는 상황을 줄이는 편이 좋습니다.'});if(metrics.humidity>=80||metrics.dewPoint>=20)advice.push({key:'humidity',title:'출발 직전에 마무리하세요',description:'습기가 높은 날에는 세팅 후 실내에서 오래 기다리기보다 외출 직전에 마무리하는 편이 낫습니다.'});if(metrics.wind>=20)advice.push({key:'wind',title:'바람 센 구간을 피하세요',description:'가능하다면 지상 보행을 줄이고 실내 연결 동선을 이용하세요.'});return advice.slice(0,3);}
  function getFeedbackLabel(type){return{survived:'유지됨',shaky:'조금 무너짐',failed:'망함'}[type]||'';}
  function feedbackDayKey(forecastTime){if(typeof forecastTime==='string'&&/^\d{4}-\d{2}-\d{2}/.test(forecastTime))return forecastTime.slice(0,10);return new Date().toISOString().slice(0,10);}
  function upsertDailyFeedback(samples,sample,maxSamples=30){const safeSamples=Array.isArray(samples)?samples.slice():[];const index=safeSamples.findIndex((entry)=>entry.day===sample.day);if(index>=0)safeSamples[index]=sample;else safeSamples.push(sample);return safeSamples.slice(-maxSamples);}
  function getDailyFeedback(samples,day){if(!Array.isArray(samples))return null;return samples.find((sample)=>sample.day===day)||null;}
  function getCalibrationOffset(samples){if(!Array.isArray(samples)||samples.length<3)return 0;const averageError=samples.reduce((sum,sample)=>sum+(sample.actualRisk-sample.predictedRisk),0)/samples.length;return clamp(averageError*.55,-.15,.15);}
  function normalizeFeedbackSample(sample){if(!sample||!Number.isFinite(sample.predictedRisk)||!Number.isFinite(sample.actualRisk))return null;const at=typeof sample.at==='string'?sample.at:new Date().toISOString();return{at,day:typeof sample.day==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(sample.day)?sample.day:at.slice(0,10),type:['survived','shaky','failed'].includes(sample.type)?sample.type:null,predictedRisk:sample.predictedRisk,actualRisk:sample.actualRisk};}
  return{clamp,smoothstep,calculateBaseRisk,calculateDewPoint,toKmaGrid,chooseKmaBaseDateTime,parseKmaForecastItems,distanceKm,isSuspiciousLocationJump,normalizeSavedLocation,getSensitivityOffset,getVerdict,getBangsAdvice,getFeedbackLabel,feedbackDayKey,upsertDailyFeedback,getDailyFeedback,getCalibrationOffset,normalizeFeedbackSample};
}));
